# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v8.3.9
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod:
  - cert_resolver: letsencrypt
    hosts:
      - outofreality.francoleyes.xyz
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: es_AR
odoo_listdb: false
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 17.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "16"
project_author: Out of reality
project_license: AGPL-3.0-or-later
project_name: out_of_reality
smtp_canonical_default: "gmail.com


  "
smtp_canonical_domains: []
smtp_default_from: 4177asd@gmail.com
smtp_relay_host: "smtp.gmail.com

  "
smtp_relay_port: 587
smtp_relay_user: "4177asd@gmail.com

  "
smtp_relay_version: "13"
traefik_version: 2
