# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v8.3.6
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: https://github.com/out-of-reality/out-of-reality
odoo_dbfilter: ^prod
odoo_initial_lang: es_AR
odoo_listdb: true
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 17.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod
postgres_exposed: true
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: "16"
project_author: Out of reality
project_license: AGPL-3.0-or-later
project_name: out-of-reality
smtp_canonical_default: ""
smtp_canonical_domains: []
smtp_default_from: ""
smtp_relay_host: "smtp.gmail.com

  "
smtp_relay_port: 587
smtp_relay_user: 4177asd@gmail.com
smtp_relay_version: "13"
traefik_version: 2
