version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_AR"
      ODOO_BUS_PUBLIC_SAMESITE_WS: 1
      SMTP_SERVER: smtplocal
      PGHOST: out-of-reality-17-0-prod-db
    depends_on:
      - db
      - smtp
    networks:
      default:
    labels:
      doodba.domain.main: ""

  db:
    extends:
      file: common.yaml
      service: db
    environment:
      DB_HOST: out-of-reality-17-0-prod-db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "out-of-reality-17-0-prod-db"
    ports:
      - "5432:5432"

  smtp:
    extends:
      file: common.yaml
      service: smtpreal
    env_file:
      - .docker/smtp.env
    networks:
      default:
        aliases:
          - smtplocal
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
  mailconfig:
  maildata:
  maillogs:
  maillogssupervisord:
  mailstate:
